// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rets_API.Data;

#nullable disable

namespace Rets_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615173737_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rets_API.Models.Exercise", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("text");

                    b.Property<string>("ExerciseImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryMuscle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Rets_API.Models.Split", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SplitId"));

                    b.Property<string>("DefaultDay")
                        .HasColumnType("text");

                    b.Property<string>("SplitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SplitId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("Rets_API.Models.SplitExercise", b =>
                {
                    b.Property<int>("SplitId")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseId")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("SplitId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("SplitExercise");
                });

            modelBuilder.Entity("Rets_API.Models.SplitExercise", b =>
                {
                    b.HasOne("Rets_API.Models.Exercise", "Exercise")
                        .WithMany("SplitExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rets_API.Models.Split", "Split")
                        .WithMany("SplitExercises")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("Rets_API.Models.Exercise", b =>
                {
                    b.Navigation("SplitExercises");
                });

            modelBuilder.Entity("Rets_API.Models.Split", b =>
                {
                    b.Navigation("SplitExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
